version: "3.9"

services:
  insurance-api:
    build: ./apps/demo-insurance/backend
    ports:
      - "8000:8000"
    depends_on:
      - otel-collector

  insurance-frontend:
    build: ./apps/demo-insurance/frontend
    ports:
      - "3000:80"
    depends_on:
      - insurance-api

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./telemetry/opentelemetry/collector.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318" # OTLP HTTP receiver
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # UI
      - "4317:4317" # OTLP gRPC
