apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-backend
  namespace: sre-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-backend
  template:
    metadata:
      labels:
        app: insurance-backend
    spec:
      containers:
      - name: backend
        image: insurance-backend:latest
        imagePullPolicy: Never # Use local image
        ports:
        - containerPort: 8000
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4318"
        - name: OTEL_SERVICE_NAME
          value: "insurance-backend-k8s"
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-api
  namespace: sre-space
spec:
  selector:
    app: insurance-backend
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-frontend
  namespace: sre-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-frontend
  template:
    metadata:
      labels:
        app: insurance-frontend
    spec:
      containers:
      - name: frontend
        image: insurance-frontend:latest
        imagePullPolicy: Never # Use local image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-frontend
  namespace: sre-space
spec:
  type: NodePort # Expose simple access
  selector:
    app: insurance-frontend
  ports:
  - port: 3000
    targetPort: 80
    nodePort: 30000
